### ISSUE TITLE
User research on Payouts with campaign organizers- to scope what we will build either to enable campaigns without auto payouts OR enable auto payouts

### ISSUE THREAD

**Issue by charmzzyyy** [datagovsg/redeem-landing#111]
# **To-do**

User research 

- [ ]  Currently most campaign organizers do not require payouts [https://docs.google.com/spreadsheets/d/1PGpfjuNABL_-d9EgK6THDuYq_4vzyfLSmJc4XD-Uezg/edit#gid=0](https://docs.google.com/spreadsheets/d/1PGpfjuNABL_-d9EgK6THDuYq_4vzyfLSmJc4XD-Uezg/edit#gid=0)
- [x]  Understand whether there are Instruction manual/ policy blockers for doing auto payouts across the board
    - [Paul] Spoke to AGD, no issue on their side. Agencies just need to apply to create a imprest account.
- [ ]  Map out which bank agencies use across the board (mostly DBS based on previous conversations but might be different)
- [ ]  Understand what is involved to contract with DBS, UOB and OCBC if we were to integrate with all 3 separately
- [x]  For ministries, understand what are the IM blockers that require them to set up an imprest account
    - [Paul] Spoke to AGD, no issue on their side. Agencies just need to apply to create a imprest account.

- Would payouts be a hard blocker for campaign organisers (like MHA)? How can we accommodate both no-payout and payout campaigns? Does it make sense to have a digital voucher system without payouts?~~~~
- What will merchant experience be like? This may not be an issue with some merchants – for instance bigger merchants not too concerned with cash flow, and might be ok with manual payouts
