### ISSUE TITLE
To-do for supermarket integration test

### ISSUE THREAD

**Issue by charmzzyyy** [datagovsg/redeem-landing#113]
### Integration Test Details
- Test Details
  - Test period: 3 October - 11 November
  - 6 Supermarket (8 API keys)
  - Test campaign  `campaign_4fedb1af-ac5a-4050-8406-604b19ffcdac`

### Integration Documents
- [x] Integration test document @charmzzyyy 
- [x] Integration test case @charmzzyyy 

### API Key Generation and Provision
- [x] Finalise merchant / user details with supermarkets @charmzzyyy 
- [x] https://github.com/datagovsg/redeem-api/issues/868 @huangkaiw3n @ihwk1996 @fabbbbbbyy 
- [x] Save API keys in `RedeemSG - Merchant` vault with format `RedeemSG - Merchant 2022 - {{Supermarket_Name}}` @huangkaiw3n @ihwk1996 @fabbbbbbyy 
- [x] Share API keys with supermarkets on 3 October @charmzzyyy 

### Set Up Testing Environment
- [x] create integration test campaign on staging @charmzzyyy
- [x] Add `Supermarket` and `Other type` voucher types to test campaign @huangkaiw3n @ihwk1996 @fabbbbbbyy
- [x] Add merchants to test campaign `Supermarket` voucher type only @huangkaiw3n @ihwk1996 @fabbbbbbyy

### Create test vouchers
- [x] https://github.com/datagovsg/redeem-api/issues/867 @huangkaiw3n @ihwk1996 @fabbbbbbyy 
- [x] Consolidate and share test vouchers with supermarket @charmzzyyy 

### Start of test
- [x] Set up whatsapp group
