### ISSUE TITLE
T3 Pre Launch Checklist

### ISSUE THREAD

**Issue by charmzzyyy** [datagovsg/redeem-landing#115]
### Feature development
- [x] https://github.com/datagovsg/redeem-voucher/issues/247 @fabbbbbbyy 
- [x] Add transaction ID to redeemed screen and transaction history
- [ ] https://github.com/datagovsg/redeem-admin/issues/566 @JasonChong96 
- [x] https://github.com/datagovsg/redeem-signup/issues/437 @fabbbbbbyy 
- [x]  https://github.com/datagovsg/redeem-api/issues/335 @talithachin 
- [x] https://github.com/datagovsg/redeem-api/issues/843 @ihwk1996 

### Engineering & Monitoring
- [x] VAPT @huangkaiw3n 
- [ ] verify indexes
- [ ] verify heavy routes
- [x] inform singpass + twilio on expected high traffic @charmzzyyy
- [ ] New stable environment for dev @ihwk1996 
- [ ] Scale up instances

### Others
- [x] Confirm dispute resolution with supermarkets @reshmaaaaaaaa 
- [x] Confirm transactions API implementations with supermarkets @reshmaaaaaaaa 
- [x] Training for admin portal and CAs / DAs
- [ ] Training for heartland merchants
- [x] Training for supermarkets chief cashiers
- [x] Confirm translations @charmzzyyy 
- [ ] Marketing (Yihan)
- [ ] Prepare technical briefing + screens & links for media to use
- [ ] AOR for Cloudflare Workers
- [ ] Update grafana metrics to differentiate heartland and supermarkets

### Setting up of CDC T3 Campaign
 **Campaign settings**
- [x] Create campaign on production `campaign_5292ab46-ae2a-486d-ac9a-4668b3165bc2`
- [x] Confirm denominations for CDC T3 campaign with CPD @charmzzyyy
- [x] Add voucher types & denominations to campaign [engineer @JasonChong96]
- [ ] Add logo to campaign @JasonChong96
- [ ] Enable payouts for T3 @ihwk1996 
- [ ] Update blacklist if neccessary

**Admin users**
- [ ] Confirm list of admin users with CPD @charmzzyyy 
- [ ] Add admin users to T3 (prod) after admin training
- [ ] Remove admin users from staging after admin training (mid Dec)
- [ ] Remove admin users from prod T1 and T2 (on 1 Jan or 3 Jan)

**Merchants** 
- [x] Copy T1 & T2 merchants to T3 'CDC Vouchers'
- [ ] Add supermarkets to T3 'CDC Supermarket Vouchers'
- [x] https://github.com/datagovsg/redeem-api/issues/891 @JasonChong96 
- [ ] Remove incentive voucher from 29 Dec @JasonChong96 

## On launch date
- [ ] Scale up production instances
- [ ] Make campaign active & public at 10am [TBC TIME] 
- [ ] Redirect go.gov.sg/cdcv if needed
- [ ] Update Redeem landing page
- [ ] Add test to datadog to monitor sign up
- [ ] Check mainstream media hyperlink

Others (good to have)
- [ ] Load test
